---------------------------------------
Begin PBS Prologue Sat Oct  8 02:13:23 EDT 2022
Job ID:     5020801.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Queue:      inferno
End PBS Prologue Sat Oct  8 02:13:23 EDT 2022
---------------------------------------
stty: standard input: Inappropriate ioctl for device
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type           | Params
----------------------------------------
0 | net  | CNNAutoEncoder | 255 K 
----------------------------------------
255 K     Trainable params
0         Non-trainable params
255 K     Total params
1.023     Total estimated model params size (MB)
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning: Checkpoint directory /storage/scratch1/4/hmanjunatha6/carnet/logs/2022-10-08/AUTOENCODER exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
pygame 2.1.2 (SDL 2.0.16, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
[1;32mRunning the block    |  carnet_autoencoder_training[0m
=>> PBS: job killed: walltime 30009 exceeded limit 30000
---------------------------------------
Begin PBS Epilogue Sat Oct  8 10:33:32 EDT 2022
Job ID:     5020801.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Resources:  nodes=1:ppn=4:gpus=1:TeslaV100-16GB,pmem=8gb,walltime=08:20:00,neednodes=1:ppn=4:gpus=1:TeslaV100-16GB
Rsrc Used:  cput=33:11:16,vmem=309058648kb,walltime=08:20:09,mem=4042004kb,energy_used=0
Queue:      inferno
Nodes:     
atl1-1-02-006-35.pace.gatech.edu
End PBS Epilogue Sat Oct  8 10:33:32 EDT 2022
---------------------------------------
---------------------------------------
Begin PBS Prologue Sun Oct  9 02:51:13 EDT 2022
Job ID:     5024915.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Queue:      inferno
End PBS Prologue Sun Oct  9 02:51:13 EDT 2022
---------------------------------------
stty: standard input: Inappropriate ioctl for device
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type              | Params
-------------------------------------------
0 | net  | ResNetAutoencoder | 519 K 
-------------------------------------------
519 K     Trainable params
0         Non-trainable params
519 K     Total params
2.078     Total estimated model params size (MB)
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning: Checkpoint directory /storage/scratch1/4/hmanjunatha6/carnet/logs/2022-10-09/AUTOENCODER exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
pygame 2.1.2 (SDL 2.0.16, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
[1;32mRunning the block    |  carnet_autoencoder_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
=>> PBS: job killed: walltime 30045 exceeded limit 30000
---------------------------------------
Begin PBS Epilogue Sun Oct  9 11:11:57 EDT 2022
Job ID:     5024915.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Resources:  nodes=1:ppn=4:gpus=1:TeslaV100-16GB,pmem=8gb,walltime=08:20:00,neednodes=1:ppn=4:gpus=1:TeslaV100-16GB
Rsrc Used:  cput=33:13:59,vmem=320566620kb,walltime=08:20:45,mem=4163020kb,energy_used=0
Queue:      inferno
Nodes:     
atl1-1-02-005-30.pace.gatech.edu
End PBS Epilogue Sun Oct  9 11:11:57 EDT 2022
---------------------------------------
---------------------------------------
Begin PBS Prologue Wed Oct 12 19:12:57 EDT 2022
Job ID:     5039725.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Queue:      inferno
End PBS Prologue Wed Oct 12 19:12:57 EDT 2022
---------------------------------------
stty: standard input: Inappropriate ioctl for device
[88mSkipping the block   |  carnet_autoencoder_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type              | Params
-------------------------------------------
0 | net  | ResNetAutoencoder | 525 K 
-------------------------------------------
525 K     Trainable params
0         Non-trainable params
525 K     Total params
2.102     Total estimated model params size (MB)
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning: Checkpoint directory /storage/scratch1/4/hmanjunatha6/carnet/logs/2022-10-12/SEGMENTATION exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
pygame 2.1.2 (SDL 2.0.16, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
[1;32mRunning the block    |  carnet_semseg_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
=>> PBS: job killed: walltime 30016 exceeded limit 30000
---------------------------------------
Begin PBS Epilogue Thu Oct 13 03:33:13 EDT 2022
Job ID:     5039725.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Resources:  nodes=1:ppn=4:gpus=1:TeslaV100-16GB,pmem=8gb,walltime=08:20:00,neednodes=1:ppn=4:gpus=1:TeslaV100-16GB
Rsrc Used:  cput=33:05:06,vmem=321528412kb,walltime=08:20:16,mem=4250176kb,energy_used=0
Queue:      inferno
Nodes:     
atl1-1-01-004-32.pace.gatech.edu
End PBS Epilogue Thu Oct 13 03:33:13 EDT 2022
---------------------------------------
---------------------------------------
Begin PBS Prologue Sat Oct 15 02:49:02 EDT 2022
Job ID:     5051615.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Queue:      inferno
End PBS Prologue Sat Oct 15 02:49:02 EDT 2022
---------------------------------------
stty: standard input: Inappropriate ioctl for device
[88mSkipping the block   |  carnet_autoencoder_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type              | Params
-------------------------------------------
0 | net  | ResNetAutoencoder | 525 K 
-------------------------------------------
525 K     Trainable params
0         Non-trainable params
525 K     Total params
2.102     Total estimated model params size (MB)
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning: Checkpoint directory /storage/scratch1/4/hmanjunatha6/carnet/logs/2022-10-15/SEGMENTATION exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
pygame 2.1.2 (SDL 2.0.16, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
[1;32mRunning the block    |  carnet_semseg_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
=>> PBS: job killed: walltime 30001 exceeded limit 30000
---------------------------------------
Begin PBS Epilogue Sat Oct 15 11:09:03 EDT 2022
Job ID:     5051615.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   imitation
Resources:  nodes=1:ppn=4:gpus=1:TeslaV100-16GB,pmem=8gb,walltime=08:20:00,neednodes=1:ppn=4:gpus=1:TeslaV100-16GB
Rsrc Used:  cput=33:16:30,vmem=322036812kb,walltime=08:20:01,mem=3649260kb,energy_used=0
Queue:      inferno
Nodes:     
atl1-1-02-005-27.pace.gatech.edu
End PBS Epilogue Sat Oct 15 11:09:03 EDT 2022
---------------------------------------
---------------------------------------
Begin PBS Prologue Sun Oct 16 04:30:32 EDT 2022
Job ID:     5053478.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   rnn_segmentation
Queue:      inferno
End PBS Prologue Sun Oct 16 04:30:32 EDT 2022
---------------------------------------
stty: standard input: Inappropriate ioctl for device
[88mSkipping the block   |  carnet_autoencoder_training[0m
[88mSkipping the block   |  carnet_semseg_training[0m
[88mSkipping the block   |  verify_autoencoder[0m
[88mSkipping the block   |  verify_segmentation[0m
[88mSkipping the block   |  carnet_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/utilities/model_summary.py:438: UserWarning: A layer with UninitializedParameter was found. Thus, the total number of parameters detected may be inaccurate.
  warning_cache.warn(

  | Name | Type      | Params
-----------------------------------
0 | net  | ResCARNet | 562 K 
-----------------------------------
562 K     Trainable params
0         Non-trainable params
562 K     Total params
2.251     Total estimated model params size (MB)
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:631: UserWarning: Checkpoint directory /storage/scratch1/4/hmanjunatha6/carnet/logs/2022-10-16/RNN_SEGMENTATION exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
pygame 2.1.2 (SDL 2.0.16, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
[1;32mRunning the block    |  rescarnet_training[0m
/storage/home/hcoda1/4/hmanjunatha6/.conda/envs/carla/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
=>> PBS: job killed: walltime 30012 exceeded limit 30000
---------------------------------------
Begin PBS Epilogue Sun Oct 16 12:50:44 EDT 2022
Job ID:     5053478.sched-torque.pace.gatech.edu
User ID:    hmanjunatha6
Job name:   rnn_segmentation
Resources:  nodes=1:ppn=4:gpus=1:TeslaV100-16GB,pmem=8gb,walltime=08:20:00,neednodes=1:ppn=4:gpus=1:TeslaV100-16GB
Rsrc Used:  cput=33:16:08,vmem=369369968kb,walltime=08:20:12,mem=5015752kb,energy_used=0
Queue:      inferno
Nodes:     
atl1-1-02-005-28.pace.gatech.edu
End PBS Epilogue Sun Oct 16 12:50:44 EDT 2022
---------------------------------------
